require "bundler/gem_tasks"
require 'rake/testtask'

task :default => :'test:all'

namespace :test do

  desc "Run all tests"
  Rake::TestTask.new(:all) do |t|
    t.libs << 'lib'
    t.test_files = FileList['test/**/*_test.rb']
    t.verbose = true
  end

end